### ISSUE TITLE
Dahua VTH script problem?

### ISSUE THREAD

**Issue by lolzor7** [Antori91/Home_Automation#1]
Hello,

I'm trying out your amazing project since I also have Dahua NVR, Dahua CAM, Dahua VTH and Dahua VTO, but I ran into somme issues!

Actually I'm just trying to use my VTH to arm and disarm my domoticz system.

Could you help me out?

I'm getting these errors when I run python3 Dahua-VTH-SecPanel.py

[*] [2020-05-28 15:22:01.297212 VTH_SecPanel-KEEPALIVE] STARTED. Ping every 60s
Traceback (most recent call last):
  File "scripts/Dahua-VTH-SecPanel.py", line 1032, in <module>
    if Dahua.Dahua_Login():
  File "scripts/Dahua-VTH-SecPanel.py", line 617, in Dahua_Login
    self.VTHCxion    = hashlib.md5(open('/home/pi/iot_domoticz/Dahua-VTH-BOX-cxion.log','rb').read()).hexdigest()
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/iot_domoticz/Dahua-VTH-BOX-cxion.log'

Also with these settings I was not sure of...

'VTO_PORT' 80
'VTO_PROTOCOL' dhip
'VTO_SERIAL_NUMBER' 123456? where can I find
'VTH_PORT' 5000
'VTH_PROTOCOL' dhip
'VTH_CREDENTIALS'  not sure what these are?
'VTH_SERIAL_NUMBER'  123456? where can I find

Thank you very much,

K.

**Comment by Antori91** [comment]
Hello,
You have ALWAYS to start the script using the shell "Dahua-VTH-SecPanel_respawn.sh". This shell generates the current missing file in your environment. Notice that you have first to personalize this "Dahua-VTH-SecPanel_respawn.sh" as mentioned at its line #4.
Regarding the VTO parameters, they are currently not used. Regarding the VTH parameters:
VTH_CREDENTIALS is usually "admin:password" where password is the activation password you have chosen when installing the VTH. To get your VTH serial number, use verbose mode by modifying line #43. Change verbose = False to verbose = True. Then, the VTH serial number found will be printed.

**Comment by lolzor7** [comment]
Oh very nice, that worked much better!

Had no errors from the script anymore, this was the output:
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

I assumed I also have to install the scripts from the _Domoticz server side scripts_ folder.

I put 3 files more onto my raspberry pi: 
WiFi_DZ_MQTT_SecretKeys.js
iot_Orchestrator_RBY.sh
iot_Orchestrator.js

Had some changes to them to fit to my folders.

I am running the script iot_Orchestrator_RBY.sh and get this output in console:
Server 'iot_Orchestrator' crashed with exit code 1. Respawning..

So I look to the iot_Orchestrator.log file and I got this added:
/home/lolzor/scripts/iot_Orchestrator.js:145
  HeatingStatus = JSON.parse( Hstatus=data.result[0].Value ); 
                                                 ^

TypeError: Cannot read property '0' of undefined
    at GetHeatersStatus (/home/lolzor/scripts/iot_Orchestrator.js:145:50)
    at IncomingMessage.<anonymous> (/home/lolzor/scripts/iot_Orchestrator.js:92:25)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:974:34)
    at resume_ (_stream_readable.js:955:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Can you help me any further?

I am trying to change the domoticz security panel's status when I arm/home or arm/away my Dahua VTH.

Greetings, 
K.

**Comment by Antori91** [comment]
Hello,
Yes, correct. You have to use the shell iot_Orchestrator_RBY.sh. 
The issue is in my environment iot_orchestrator.js do many things you don't care. If you don't want to customize iot_Orchestrator.js, you have to add the following Domoticz **user variable** to avoid the issue you get at line 145:
Idx=1, "String", name "HeatersActive", initial value: {"command" : "activateheaters", "28" : "On", "29" : "On", "27" : "On", "30" : "On", "31" : "On", "35" : "On", "36" : "On", "37" : "Off", "38" : "On", "34" : "On"}
Notice that the numbers 27, 28, 29, .. are in my environment IDX of dummy P1 smart Meter.

**Comment by lolzor7** [comment]
Hello,

Still trying to get this to work.

Now I am receiving MQTT messages in domoticz/out topic.

{"Battery": 255, "RSSI": "3642898ec04f32e7bbe4ea53dddc7930", "description": {"stationID": "------------", "datetime": "2020-06-02 12:07:33.720358", "nvalue": 9}, "dtype": "Security", "id": "148702", "idx": "16", "name": "Security Panel", "nvalue": 9, "stype": "Security Panel", "switchType": "On/Off", "unit": 0}

Is this the output from this line in iot_Orchestrator?

> `     if(topic === 'domoticz/out' && JSONmessage.idx === MyJSecretKeys.idx_SecPanel) {     // message coming from another alarm client. Synchronize local Dz Secpanel
>           if( (JSONmessage.RSSI != crypto.createHash('md5').update(JSON.stringify(JSONmessage.description)+MyJSecretKeys.SecPanel_Seccode).digest('hex')) ||  ( ( (new Date() - new Date( JSONmessage.description.datetime )) / 1000 ) > 2 )  )
>               console.log("\n*** " + new Date() + " SECURITY WARNING - Message with invalid MD5 hash or datetime stamp received" );
>           else if( JSONmessage.description.stationID != MyJSecretKeys.DZ_ALARM_CID) {
>               if( !VERBOSE ) console.log("\n*** " + new Date() + " MQTT MD5 signed message about Alarm Request received: " + message);
>               JSON_API.path = '/json.htm?type=command&param=getsecstatus'
>               JSON_API.path = JSON_API.path.replace(/ /g,"");
>               DomoticzJsonTalk( JSON_API, updateSecPanel, JSONmessage );           
>           } // else if( JSONmessage.description.stationID != MyJS
>      }
> `

But still my domoticz alarm panel isn't updating to my vth status.

What should I do now ? For the moment I'm not receiving errors anymore. (I commented them out)


Thanks again,
K.

**Comment by Antori91** [comment]
Hello,

It seems you didn't initialize: 
'SVR_ALARM_SID'              : 'XXX',  # Alarm Server network SID
'DZ_ALARM_CID'                : 'YYY',   # Dz Alarm network CID
'VTH_ALARM_CID'              : 'ZZZ-VTH',  # VTH Alarm network CID
'VTO_ALARM_CID'              : 'ZZZ-VTO'   # VTO Alarm network CID
They are ID that help identify who sent a message (SID or CID for Server or Client ID). You will see this SID/CID in the MD5 signed MQTT message as stationID.

More important, did you setup correctly idx_SecPanel, DZ_idx_SecPanel and SecPanel_Seccode. 
DZ_idx_SecPanel must be the idx of your Domoticz SecPanel (it is one or two digits number).  idx_SecPanel is an non Domoticz IDX used by VTH (and alarm server in my environment). It is a string. To summarize, let say your Domoticz SecPanel (DZ_idx_SecPanel) idx is 1, you could choose '1' for  idx_SecPanel

Cheers,

**Comment by Antori91** [comment]
Here are examples of message in Dahua-VTH-SecPanel.log when arming/disarming form the VTH screen or from the Domoticz Secpanel (I've changed my idx and stationID, not the ones I use):

Arming from VTH >>>
[*] [2020-05-14 17:16:28.228789 VTH_SecPanel-AlarmToken] updated from VTH BOX to: {'Battery': 255, 'RSSI': '44d3d0dd36fef593b453886207065e20', 'description': {'stationID': '-VTH', 'datetime': '2020-05-09 18:21:44.836742', 'nvalue': 9}, 'dtype': 'Security', 'id': '148702', 'idx': '9', 'name': 'Security Panel', 'nvalue': 9, 'stype': 'Security Panel', 'switchType': 'On/Off', 'unit': 0}
[*] [2020-05-14 17:16:28.236398 VTH_SecPanel and VTH_BOX] FOLLOWING VTH USER OPERATION, SUCCESSFULL ALARM STATE MODIFICATION. VTH AlarmEnable is now: True
[*] [2020-05-14 17:16:28.237494 VTH_SecPanel-MQTT_TX] {'Battery': 255, 'RSSI': '880e649620cdc81e6c8bda01fbf39b22', 'description': {'stationID': '-VTH', 'datetime': '2020-05-14 17:16:28.237200', 'nvalue': 9}, 'dtype': 'Security', 'id': '148702', 'idx': '9', 'name': 'Security Panel', 'nvalue': 9, 'stype': 'Security Panel', 'switchType': 'On/Off', 'unit': 0}
[*] [2020-05-14 17:16:28.242582 VTH_SecPanel-MQTT_RX] {'Battery': 255, 'RSSI': '880e649620cdc81e6c8bda01fbf39b22', 'description': {'stationID': '-VTH', 'datetime': '2020-05-14 17:16:28.237200', 'nvalue': 9}, 'dtype': 'Security', 'id': '148702', 'idx': '9', 'name': 'Security Panel', 'nvalue': 9, 'stype': 'Security Panel', 'switchType': 'On/Off', 'unit': 0}
[*] [2020-05-14 17:16:28.531734 VTH_SecPanel-MQTT_RX] {'Battery': 255, 'RSSI': '9c0283f075f8986135cc784f5785597c', 'description': {'stationID': '-DZ', 'datetime': '2020-05-14 17:16:28.467000', 'nvalue': 9}, 'dtype': 'Security', 'id': '148702', 'idx': '9', 'name': 'Security Panel', 'nvalue': 9, 'stype': 'Security Panel', 'switchType': 'On/Off', 'unit': 0}

Then disarming from Domoticz a few minutes after >>>
[*] [2020-05-14 17:19:33.287355 VTH_SecPanel-MQTT_RX] {'Battery': 255, 'RSSI': 'acfc0bda589a606a5986721819692f82', 'description': {'stationID': '-DZ', 'datetime': '2020-05-14 17:19:33.285000', 'nvalue': 0}, 'dtype': 'Security', 'id': '148702', 'idx': '9', 'name': 'Security Panel', 'nvalue': 0, 'stype': 'Security Panel', 'switchType': 'On/Off', 'unit': 0}
[*] [2020-05-14 17:19:34.209509 VTH_SecPanel and VTH_BOX] FOLLOWING MQTT MESSAGE, SUCCESSFULL ALARM STATE MODIFICATION. VTH AlarmEnable is now: False

**Comment by lolzor7** [comment]
Hey,

Both are set to my IDX number of my domoticz alarm device (in WiFi_DZ_MQTT_SecretKeys and also in VTOH_DZ_MQTT_SecretKeys

idx_SecPanel               : '16',                               //                       - Alarm Server Security Panel (MD5 signed message)
DZ_idx_SecPanel            :  16,                                //[$$DOMOTICZ_PARAMETER] - Dz Security Panel

secpanel seccode is also set to my password from the secpanel.

greets

**Comment by Antori91** [comment]
If  you still have issues, take a look in the two log files Dahua-VTH-SecPanel.log
and iot_Orchestrator.log.

**Comment by Antori91** [comment]
About secpanel seccode, it is not the Domoticz Secpanel password but the SecPanel password MD5 encrypted. Take a look if necessary in the Domoticz documentation.

**Comment by lolzor7** [comment]
So that did work out for me, now the secpanel changes accordingly and syncs to my vth status. Thanks for that!
But i still have some errors in my log files though.. :(

Dahua-VTH_SecPanel

> [*] [2020-06-02 13:53:00.061220 VTH_SecPanel-KEEPALIVE] STARTED. Ping every 60s
> [+] [2020-06-02 13:53:00.588603 VTH-P2P_OK] CONNECTED to VTH BOX
> [*] [2020-06-02 13:53:01.105619 VTH_SecPanel-AlarmToken] updated from VTH BOX to: {'Battery': 255, 'RSSI': '', 'description': 'vthalarmnetworkcid', 'dtype': 'Security', 'id': '148702', 'idx': '16', 'name': 'Security Panel', 'nvalue': 0, 'stype': 'Security Panel', 'switchType': 'On/Off', 'unit': 0}
> [*] [2020-06-02 13:53:30.052801 VTH_SecPanel-MQTT_TX] {'command': 'addlogmessage', 'message': 'VTH SECPANEL ON LINE'}
> [*] [2020-06-02 13:53:30.057516 VTH_SecPanel-MQTT_TX] {'command': 'addlogmessage', 'message': 'VTH BOX ON LINE'}
> [*] [2020-06-02 13:53:30.061326 VTH_SecPanel-MQTT_TX] {'command': 'getdeviceinfo', 'idx': 16}
> [*] [2020-06-02 13:53:30.064874 VTH_SecPanel-MQTT_TX] {'command': 'getdeviceinfo', 'idx': 22}
> [*] [2020-06-02 13:53:30.364479 VTH_SecPanel-MQTT_RX] {'Battery': 255, 'RSSI': 12, 'description': '', 'dtype': 'Lighting 1', 'hwid': '3', 'id': '65', 'idx': 22, 'name': 'ALM_INBRAAK', 'nvalue': 0, 'stype': 'X10', 'switchType': 'On/Off', 'unit': 2}
> [*] [2020-06-02 13:53:30.568764 VTH_SecPanel-MQTT_RX] {'Battery': 255, 'RSSI': 12, 'description': '', 'dtype': 'Lighting 1', 'hwid': '3', 'id': '65', 'idx': 22, 'name': 'ALM_INBRAAK', 'nvalue': 0, 'stype': 'X10', 'switchType': 'On/Off', 'unit': 2}
> [*] [2020-06-02 13:53:30.670322 VTH_SecPanel-MQTT_RX] {'Battery': 255, 'RSSI': 12, 'description': '', 'dtype': 'Lighting 1', 'hwid': '3', 'id': '65', 'idx': 22, 'name': 'ALM_INBRAAK', 'nvalue': 0, 'stype': 'X10', 'switchType': 'On/Off', 'unit': 2}

iot_Orchestrator

> *** Tue Jun 02 2020 13:53:30 GMT+0200 (Central European Summer Time) New MQTT message about local Secpanel received: {
> 	"Battery" : 255,
> 	"RSSI" : 12,
> 	"description" : "",
> 	"dtype" : "Security",
> 	"hwid" : "1",
> 	"id" : "148702",
> 	"idx" : 16,
> 	"name" : "Domoticz Security Panel",
> 	"nvalue" : 0,
> 	"stype" : "Security Panel",
> 	"switchType" : "On/Off",
> 	"unit" : 0
> }
> 
> undefined:1
> {"command" : "switchlight", "idx" : 22, "switchcmd" : "Set Level", "level" : undefined, "passcode" : XXXXXX}
>                                                                              ^

mqtt cluster

> [Tue Jun 02 2020 13:52:48 GMT+0200 (Central European Summer Time) mtCluster-Info] Server: MAIN, Service: MQTT, Status: ON LINE
> 
> [Tue Jun 02 2020 13:52:48 GMT+0200 (Central European Summer Time) mtCluster-Info] Server: BACKUP, Service: MQTT, Status: ON LINE
> undefined:1
> {"command" : "switchlight", "idx" : 22, "switchcmd" : "Set Level", "level" : undefined, "passcode" : XXXXXX}
>                                                                              ^
> 
> SyntaxError: Unexpected token u in JSON at position 77
>     at JSON.parse (<anonymous>)
>     at MqttClient.<anonymous> (/home/lolzor/scripts/mqtt_Cluster.js:442:27)
>     at MqttClient.emit (events.js:198:13)
>     at MqttClient._handlePublish (/home/lolzor/node_modules/mqtt/lib/client.js:1269:12)
>     at MqttClient._handlePacket (/home/lolzor/node_modules/mqtt/lib/client.js:409:12)
>     at work (/home/lolzor/node_modules/mqtt/lib/client.js:320:12)
>     at process._tickCallback (internal/process/next_tick.js:61:11)
>

**Comment by Antori91** [comment]
> That works out
> Waw really great project!
> Looks like the vth also syncs to the domoticz secpanel and reverse
> nice nice nice thumbs up and great work! (y)

Thanks, I really appreciate your comment.

**Comment by Antori91** [comment]
Your latest issue is with idx 22 
[] [2020-06-02 13:53:30.064874 VTH_SecPanel-MQTT_TX] {'command': 'getdeviceinfo', 'idx': 22}
coming from 
dzAlarmFAILURE = {
    "command" : "getdeviceinfo",
    "idx"     : mySecretKeys[ "idx_AlarmFailureFlag" ]
}

You don't have to use mqtt_Cluster.js  unless you have a cluster. But this is another topic.

**Comment by Antori91** [comment]
AlarmFailureFlag is a protected device in my environment. You have to initialize 'ProtectedDevicePassword'    : '9999',                             #[$$DOMOTICZ_PARAMETER] - Dz password for protected device
AlarmFailureFlag device is switched on when there is a issue with the alarm subsystem, especially MQTT will message.
